#!/usr/bin/env bash
# scripts/create-domain-maps.sh
# Generates domain sidecar stubs (OKF front‑matter + section placeholders)
# from the stubs AST graph.
set -uo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"
DB="${PROJECT_ROOT}/.stubs/graph.sqlite"
MAP_DIR="${PROJECT_ROOT}/knowledge/architecture/domains"

if [[ ! -f "$DB" ]]; then
  echo "❌ Stubs graph not found at $DB" >&2
  echo "   Run 'npx stubs scan .' first." >&2
  exit 1
fi

mkdir -p "$MAP_DIR"

DOMAIN_GROUPS="apps/computer|apps/mobile|apps/server|apps/worker|packages/domain|packages/integrations|packages/backends"

get_display_name() {
  case "$1" in
    "apps/computer")       echo "Computer" ;;
    "apps/mobile")         echo "Mobile" ;;
    "apps/server")         echo "Server" ;;
    "apps/worker")         echo "Browser Worker" ;;
    "packages/domain")     echo "Domain" ;;
    "packages/integrations") echo "Integrations" ;;
    "packages/backends")   echo "Backends" ;;
    *)                     echo "$1" ;;
  esac
}

get_slug() {
  echo "$1" | tr '/' ' ' | tr ' ' '-'
}

write_domain_map() {
  local group="$1"
  local display="$2"
  local slug
  slug=$(get_slug "$group")
  local md_path="${MAP_DIR}/${slug}-domain-map.md"

  local subs
  subs=$(sqlite3 "$DB" "
    SELECT DISTINCT
      substr(file_path, instr(file_path, '${group}/') + length('${group}') + 1,
             instr(substr(file_path, instr(file_path, '${group}') + length('${group}') + 2), '/') - 1) AS sub
    FROM graph_nodes
    WHERE file_path LIKE '${group}/%'
      AND file_path NOT LIKE '%.md'
      AND substr(file_path, instr(file_path, '${group}') + length('${group}') + 1, 1) = '/'
      AND instr(substr(file_path, instr(file_path, '${group}') + length('${group}') + 2), '/') > 0
    ORDER BY sub;
  " | grep -v '^$')

  local subsystem_rows=""
  if [[ -n "$subs" ]]; then
    while IFS= read -r s; do
      [[ -n "$s" ]] && subsystem_rows+="  | \`${s}\` | | [Subsystem](${slug}/${s}/subsystem-index.md) |"$'\n'
    done <<< "$subs"
  fi

  cat > "$md_path" <<EOF
---
okfVersion: "1.0.0"
id: ${slug}-domain
type: subsystem-index
title: "${display} Domain"
description: "${display} domain — core modules under ${group}"
version: 1
target_code_file: ""
status_flag: clean
status: skeleton
tags: ["${slug}", "domain"]
compliance: "standalone"
decision: "pending"
---

# ${display} Domain

Source directory: \`${group}\`

## Scope

The \`${display}\` domain owns all source files under the \`${group}\` directory.
This collection groups together related subsystems that share a common purpose
within the OpenMuse application architecture.

## Subsystems

| Subsystem | Responsibility | Context Map |
| :--- | :--- | :--- |
${subsystem_rows}
## Key concepts

Core abstractions for \`${display}\`: modules, interfaces, and data models
  defined by the source files under the domain's root directory. Invariants: consistency
  across imports/exports tracked by \`.stubs/graph.sqlite\`. Terminology: subsystem, hub node, domain prefix.

## Decisions (locked)

DEC-1 (pending): Scope boundary uses first two \`file_path\` components (\`substr\`) from \`.stubs/graph.sqlite\`. Status: proposal; needs user confirmation; consequence: defines which files belong to the domain map.

## Open questions (frontier)

Open: Does the domain boundary (\`substr(file_path, ...)\`) correctly capture sub\-folders for nested packages? Should \`subsystem-index.md\` link to real code files or remain structural? When should a domain move from \`status: skeleton\` to \`materialized\`?

## Implementation plan

1) Confirm domain boundary matches user intent (step: review \`stubs scan\` output). 2) Author descriptive \`description\` and lock \`DEC-1\` (step: user edit). 3) Materialize any \`## Implementation\` code blocks (step: \`stubs materialize\` if needed). 4) Reconcile hashes (step: \`stubs reconcile\`). 5) Cross\-repo portability check (step: copy script + \`.stubs\` to another repo). References: \`.stubs/graph.sqlite\`, \`scripts/create-domain-maps.sh\`, \`stubs-sidecar-workflow\` skill.

<!--
  Auto\u2011generated by scripts/create-domain-maps.sh
  Edit the front\u2011matter and body; the stubs CLI will reconcile hashes.
-->
EOF

  echo "  ✅  ${md_path}"
}

echo "🔍  Scanning graph for domain prefixes…"

IFS='|' read -ra groups <<< "$DOMAIN_GROUPS"

for group in "${groups[@]}"; do
  if sqlite3 "$DB" "SELECT 1 FROM graph_nodes WHERE file_path LIKE '${group}/%' LIMIT 1;" | grep -q 1; then
    display=$(get_display_name "$group")
    echo "Writing sidecar  ${group}  →  ${display}"
    write_domain_map "$group" "$display"
  else
    echo "  ⏭  ${group} – no files in graph, skipping."
  fi
done

echo ""
echo "✅  Domain maps generated in ${MAP_DIR}"